# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 120, 651, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 2)
        self.show_label_d = QtWidgets.QLabel(self.layoutWidget)
        self.show_label_d.setText("")
        self.show_label_d.setObjectName("show_label_d")
        self.gridLayout.addWidget(self.show_label_d, 1, 3, 1, 2)
        self.name_chooser = QtWidgets.QComboBox(self.layoutWidget)
        self.name_chooser.setObjectName("name_chooser")
        self.gridLayout.addWidget(self.name_chooser, 1, 0, 1, 1)
        self.show_label_g = QtWidgets.QLabel(self.layoutWidget)
        self.show_label_g.setText("")
        self.show_label_g.setObjectName("show_label_g")
        self.gridLayout.addWidget(self.show_label_g, 1, 2, 1, 1)
        self.show_label_s = QtWidgets.QLabel(self.layoutWidget)
        self.show_label_s.setText("")
        self.show_label_s.setObjectName("show_label_s")
        self.gridLayout.addWidget(self.show_label_s, 1, 1, 1, 1)
        self.show_label_p = QtWidgets.QLabel(self.layoutWidget)
        self.show_label_p.setText("")
        self.show_label_p.setObjectName("show_label_p")
        self.gridLayout.addWidget(self.show_label_p, 1, 5, 1, 1)
        self.show_label_v = QtWidgets.QLabel(self.layoutWidget)
        self.show_label_v.setText("")
        self.show_label_v.setObjectName("show_label_v")
        self.gridLayout.addWidget(self.show_label_v, 1, 6, 1, 1)
        self.addButton = QtWidgets.QPushButton(self.layoutWidget)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 2, 2, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Coffee"))
        self.label_6.setText(_translate("MainWindow", "Объем"))
        self.label_5.setText(_translate("MainWindow", "Цена"))
        self.label.setText(_translate("MainWindow", "Название"))
        self.label_2.setText(_translate("MainWindow", "Степень обжарки"))
        self.label_3.setText(_translate("MainWindow", "Молотый?"))
        self.label_4.setText(_translate("MainWindow", "Описание"))
        self.addButton.setText(_translate("MainWindow", "Добавить кофе"))
